fix(token_provider): avoid concurrent token refresh
inloco/incognia-go pull request #32
Opened 2022-01-26 20:35 UTC by lucasbarross

https://github.com/inloco/incognia-go/issues/31

2022-01-26 21:23 UTC, t0rr3sp3dr0 requested changes

2022-01-26 21:23 UTC, t0rr3sp3dr0 commented on token_provider.go
> +	tokenMutex  sync.Mutex
Use sync.RWMutex instead. Otherwise, all requests using the same client will need to acquire the lock before running, effectively creating a queue.

2022-01-27 17:24 UTC, alangalvino approved these changes

2022-01-28 12:43 UTC, gaabs approved these changes

2022-01-28 18:12 UTC, t0rr3sp3dr0 requested changes

2022-01-28 18:12 UTC, t0rr3sp3dr0 commented on token_provider.go
> +		unlockOnce.Do(t.tokenMutex.RUnlock)
Extract this to a function or reorganize the code so you don't have to unlock the token in multiple places.

```suggestion
	t.tokenMutex.RLock()
	token := t.token
	t.tokenMutex.RUnlock()

	if token == nil || token.IsExpired() {
```

2022-01-28 18:19 UTC, t0rr3sp3dr0 commented on token_provider.go
> +		unlockOnce.Do(t.tokenMutex.RUnlock)
Also, the earliest return in this case is inverted. You should return token earlier than t.refresh(), as the former is constant.

```go
if token != nil && !token.IsExpired() {
	return token, nil
}

return t.refresh()
```

2022-01-28 18:22 UTC, t0rr3sp3dr0 approved these changes

2022-01-28 18:23 UTC, merged